//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBankingASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMovement
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int fk_bankAccount { get; set; }
        public Nullable<double> @in { get; set; }
        public Nullable<double> @out { get; set; }
        public string description { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
    }
}
